apply plugin: 'com.android.application'

android {
    compileSdk 34

    defaultConfig {
        applicationId "de.htwberlin.f4.ma.indoorroutefinder"
        minSdkVersion 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        setProperty("archivesBaseName", "Indoor Route Finder")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    namespace 'de.htwberlin.f4.ai.ma.indoorroutefinder'

    configurations {
        implementation.exclude group: 'nz.ac.waikato.cms.weka.thirdparty', module: 'java-cup-11b-runtime'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.preference:preference:1.2.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    def appcompat_version = "1.6.1"

    implementation "androidx.appcompat:appcompat:$appcompat_version"
    implementation "androidx.appcompat:appcompat-resources:$appcompat_version"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.7.3'
    testImplementation 'org.mockito:mockito-core:4.2.0'


    androidTestImplementation 'androidx.test:core:1.4.0'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.2.0"
    implementation 'com.google.android.gms:play-services-vision:20.1.3'

    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'

    implementation 'com.github.haifengl:smile-core:2.6.0'

    implementation group: 'nz.ac.waikato.cms.weka', name: 'weka-stable', version: '3.8.0'

    // https://mvnrepository.com/artifact/nz.ac.waikato.cms.weka/LibSVM
    implementation files('libs/androidlibsvm-release.aar')
}
